<template>
  <div class="loading">
    <svg
      width="168"
      height="173"
      viewBox="0 0 168 173"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <mask
        id="mask0"
        mask-type="alpha"
        maskUnits="userSpaceOnUse"
        x="-1"
        y="-1"
        width="170"
        height="174"
      >
        <path
          d="M-5.33255e-05 83.4693C-4.91916e-05 36.1828 34.9084 0.41814 82.1949 0.418144C129.481 0.418149 167.815 38.7514 167.815 86.0379C167.815 133.324 129.481 171.658 82.1949 171.658C34.9084 171.658 -5.74594e-05 130.756 -5.33255e-05 83.4693Z"
          fill="#1A1A1A"
          stroke="white"
          stroke-width="1.71239"
          class="svg-elem-1"
        />
      </mask>
      <g mask="url(#mask0)">
        <rect y="161" width="168" height="17" fill="#6E65B1" class="svg-elem-2" />
        <rect y="137" width="168" height="17" fill="#6E65B1" class="svg-elem-3" />
        <rect y="117" width="168" height="13" fill="#6E65B1" class="svg-elem-4" />
        <rect y="101" width="168" height="9" fill="#6E65B1" class="svg-elem-5" />
        <rect y="90" width="168" height="4" fill="#6E65B1" class="svg-elem-6" />
        <rect y="80" width="168" height="3" fill="#6E65B1" class="svg-elem-7" />
        <rect y="71" width="168" height="2" fill="#6E65B1" class="svg-elem-8" />
        <rect y="62" width="168" height="2" fill="#6E65B1" class="svg-elem-9" />
        <rect y="53" width="168" height="2" fill="#6E65B1" class="svg-elem-10" />
        <rect y="44" width="168" height="2" fill="#6E65B1" class="svg-elem-11" />
        <rect y="35" width="168" height="2" fill="#6E65B1" class="svg-elem-12" />
        <rect y="26" width="168" height="2" fill="#6E65B1" class="svg-elem-13" />
        <rect y="17" width="168" height="2" fill="#6E65B1" class="svg-elem-14" />
        <rect y="7.99997" width="168" height="2" fill="#6E65B1" class="svg-elem-15" />
        <rect y="-3.05176e-05" width="168" height="2" fill="#6E65B1" class="svg-elem-16" />
      </g>
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M98.9703 29.3657C84.9944 42.4476 76.2605 61.0612 76.2605 81.7148C76.2605 121.308 108.357 153.405 147.951 153.405C153.964 153.405 159.805 152.664 165.387 151.269C152.571 163.266 135.347 170.61 116.407 170.61C76.8136 170.61 44.7169 138.514 44.7169 98.9204C44.7169 65.341 67.8037 37.1538 98.9703 29.3657Z"
        fill="#1A1A1A"
        class="svg-elem-17"
      />
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M101.478 28L99.4602 29.889C85.6231 42.841 76.9774 61.2677 76.9774 81.7148C76.9774 120.912 108.753 152.688 147.951 152.688C153.905 152.688 159.688 151.955 165.213 150.574L167.895 149.904L165.877 151.793C152.933 163.909 135.536 171.327 116.407 171.327C76.4177 171.327 44 138.91 44 98.9204C44 65.0042 67.3183 36.5361 98.7965 28.6701L101.478 28ZM96.4873 30.7805C66.9861 39.3901 45.4338 66.6392 45.4338 98.9204C45.4338 138.118 77.2096 169.894 116.407 169.894C134.169 169.894 150.406 163.37 162.854 152.586C158.044 153.593 153.059 154.122 147.951 154.122C107.961 154.122 75.5436 121.704 75.5436 81.7148C75.5436 61.8547 83.5402 43.8613 96.4873 30.7805Z"
        fill="#6E65B1"
        class="svg-elem-18"
      />
    </svg>
  </div>
</template>

<style lang="scss" scoped>
.loading {
    z-index: 99999;
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: #1a1a1a;
  display: flex;
  justify-content: center;
  align-items: center;
  animation: loadingLeave 1.8s linear forwards;
  animation-delay: 0.3s;

  @keyframes loadingLeave {
    88% {
      opacity: 1;
      z-index: 9999;
      transform: scale(1);
    }
    100% {
      opacity: 0;
      display: none;
      z-index: -9999;
      transform: scale(0.9);
    }
  }

  svg {
    animation: loadingLeave 1.8s linear forwards;
  }
}
/***************************************************
 * Generated by SVG Artista on 8/28/2019, 12:32:56 PM
 **************************************************/

@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 535.5656127929688px;
    stroke-dasharray: 535.5656127929688px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 535.5656127929688px;
    stroke-dasharray: 535.5656127929688px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(26, 26, 26);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(26, 26, 26);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-stroke-1 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
    animate-svg-fill-1 0.4s ease-in 0.05s both;
  animation: animate-svg-stroke-1 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0s
      both,
    animate-svg-fill-1 0.4s ease-in 0.05s both;
}

@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 372px;
    stroke-dasharray: 372px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 372px;
    stroke-dasharray: 372px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-stroke-2 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.05s both,
    animate-svg-fill-2 0.4s ease-in 0.1s both;
  animation: animate-svg-stroke-2 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.05s
      both,
    animate-svg-fill-2 0.4s ease-in 0.1s both;
}

@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 372px;
    stroke-dasharray: 372px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 372px;
    stroke-dasharray: 372px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-stroke-3 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.1s both,
    animate-svg-fill-3 0.4s ease-in 0.15000000000000002s both;
  animation: animate-svg-stroke-3 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.1s
      both,
    animate-svg-fill-3 0.4s ease-in 0.15000000000000002s both;
}

@-webkit-keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 364px;
    stroke-dasharray: 364px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 364px;
    stroke-dasharray: 364px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-stroke-4 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.15000000000000002s both,
    animate-svg-fill-4 0.4s ease-in 0.2s both;
  animation: animate-svg-stroke-4 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.15000000000000002s both,
    animate-svg-fill-4 0.4s ease-in 0.2s both;
}

@-webkit-keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 356px;
    stroke-dasharray: 356px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 356px;
    stroke-dasharray: 356px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-stroke-5 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s both,
    animate-svg-fill-5 0.4s ease-in 0.25s both;
  animation: animate-svg-stroke-5 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s
      both,
    animate-svg-fill-5 0.4s ease-in 0.25s both;
}

@-webkit-keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 346px;
    stroke-dasharray: 346px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 346px;
    stroke-dasharray: 346px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-stroke-6 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.25s both,
    animate-svg-fill-6 0.4s ease-in 0.3s both;
  animation: animate-svg-stroke-6 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.25s
      both,
    animate-svg-fill-6 0.4s ease-in 0.3s both;
}

@-webkit-keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 344px;
    stroke-dasharray: 344px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 344px;
    stroke-dasharray: 344px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-stroke-7 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.30000000000000004s both,
    animate-svg-fill-7 0.4s ease-in 0.35000000000000003s both;
  animation: animate-svg-stroke-7 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.30000000000000004s both,
    animate-svg-fill-7 0.4s ease-in 0.35000000000000003s both;
}

@-webkit-keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-stroke-8 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.35000000000000003s both,
    animate-svg-fill-8 0.4s ease-in 0.4s both;
  animation: animate-svg-stroke-8 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.35000000000000003s both,
    animate-svg-fill-8 0.4s ease-in 0.4s both;
}

@-webkit-keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-stroke-9 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s both,
    animate-svg-fill-9 0.4s ease-in 0.45s both;
  animation: animate-svg-stroke-9 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s
      both,
    animate-svg-fill-9 0.4s ease-in 0.45s both;
}

@-webkit-keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-stroke-10 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.45s both,
    animate-svg-fill-10 0.4s ease-in 0.5s both;
  animation: animate-svg-stroke-10 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.45s both,
    animate-svg-fill-10 0.4s ease-in 0.5s both;
}

@-webkit-keyframes animate-svg-stroke-11 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-11 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-11 {
  -webkit-animation: animate-svg-stroke-11 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.5s both,
    animate-svg-fill-11 0.4s ease-in 0.55s both;
  animation: animate-svg-stroke-11 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.5s
      both,
    animate-svg-fill-11 0.4s ease-in 0.55s both;
}

@-webkit-keyframes animate-svg-stroke-12 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-12 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-12 {
  -webkit-animation: animate-svg-stroke-12 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.55s both,
    animate-svg-fill-12 0.4s ease-in 0.6000000000000001s both;
  animation: animate-svg-stroke-12 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.55s both,
    animate-svg-fill-12 0.4s ease-in 0.6000000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-13 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-13 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-13 {
  -webkit-animation: animate-svg-stroke-13 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.6000000000000001s both,
    animate-svg-fill-13 0.4s ease-in 0.6500000000000001s both;
  animation: animate-svg-stroke-13 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.6000000000000001s both,
    animate-svg-fill-13 0.4s ease-in 0.6500000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-14 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-14 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-14 {
  -webkit-animation: animate-svg-stroke-14 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.65s both,
    animate-svg-fill-14 0.4s ease-in 0.7000000000000001s both;
  animation: animate-svg-stroke-14 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.65s both,
    animate-svg-fill-14 0.4s ease-in 0.7000000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-15 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-15 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-15 {
  -webkit-animation: animate-svg-stroke-15 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.7000000000000001s both,
    animate-svg-fill-15 0.4s ease-in 0.7500000000000001s both;
  animation: animate-svg-stroke-15 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.7000000000000001s both,
    animate-svg-fill-15 0.4s ease-in 0.7500000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-16 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-16 {
  0% {
    stroke-dashoffset: 342px;
    stroke-dasharray: 342px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-16 {
  -webkit-animation: animate-svg-stroke-16 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.75s both,
    animate-svg-fill-16 0.4s ease-in 0.8s both;
  animation: animate-svg-stroke-16 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.75s both,
    animate-svg-fill-16 0.4s ease-in 0.8s both;
}

@-webkit-keyframes animate-svg-stroke-17 {
  0% {
    stroke-dashoffset: 452.5049133300781px;
    stroke-dasharray: 452.5049133300781px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-17 {
  0% {
    stroke-dashoffset: 452.5049133300781px;
    stroke-dasharray: 452.5049133300781px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(26, 26, 26);
  }
}

@keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(26, 26, 26);
  }
}

.svg-elem-17 {
  -webkit-animation: animate-svg-stroke-17 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both,
    animate-svg-fill-17 0.4s ease-in 0.8500000000000001s both;
  animation: animate-svg-stroke-17 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s
      both,
    animate-svg-fill-17 0.4s ease-in 0.8500000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-18 {
  0% {
    stroke-dashoffset: 903.007080078125px;
    stroke-dasharray: 903.007080078125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-18 {
  0% {
    stroke-dashoffset: 903.007080078125px;
    stroke-dasharray: 903.007080078125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

@keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(110, 101, 177);
  }
}

.svg-elem-18 {
  -webkit-animation: animate-svg-stroke-18 0.2s
      cubic-bezier(0.47, 0, 0.745, 0.715) 0.8500000000000001s both,
    animate-svg-fill-18 0.4s ease-in 0.9000000000000001s both;
  animation: animate-svg-stroke-18 0.2s cubic-bezier(0.47, 0, 0.745, 0.715)
      0.8500000000000001s both,
    animate-svg-fill-18 0.4s ease-in 0.9000000000000001s both;
}
</style>